# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# See https://starship.rs/config/

# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$directory\
$git_state\
$cmd_duration\
$nodejs\
$rust\
$python\
$line_break\
$character"""

right_format = "$time"

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

[line_break]
disabled = true

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[nodejs]
version_format = '${major}'
format = "[$symbol($version)](green) "

[rust]
version_format = '${major}.${minor}'
format = "[$symbol($version)](red) "
