# npmPublishAccess: public # Uncomment if you want to publish packages with `yarn npm publish`

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.0.2.cjs
